services:
  _defaults:
    public: true

  # Module
  prestashop.module.nodeless:
    class: Nodeless

  # Repositories
  prestashop.module.nodeless.repository:
    class: NodelessIO\Prestashop\PaymentRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
