name: Build release artifact.
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: Build release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: nodeless
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          extensions: bcmath
      - name: Install Composer dependencies
        run: |
          cd nodeless
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Create release artifact.
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'nodeless.zip'
          exclusions: '*.git* *.github* composer.* output.log DOCKER_ENV docker_tag Dockerfile-php-build'
      - name: Upload artifact to release page.
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'nodeless.zip'
          removeArtifacts: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
