name: Build release artifact.
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: Build release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.0

      - name: Create release artifact.
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'nodeless.zip'
          exclusions: '*.git* *.github* composer.* README.md'
      - name: Upload artifact to release page.
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'nodeless.zip'
          removeArtifacts: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
